# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_stall',
            new_name='is_stalf',
        ),
    ]
